production:
  adapter: postgresql
  encoding: unicode
  database: ipx_mock_production
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: ipx_mock_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ipx_mock_test
  pool: 5